/*
 * Class name : addingReceptionist.java
 *
 * Created on May 5, 2009, 10:39 AM
 *
 * Last Modified on June 12, 2009
 *
 * Why was this class created?
 * This class which is a GUI will allow the admin to create a new receptionist user
 * for the system who will have all system privelages available to a user.
 */

package hospital_project;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/*
 * @author  MHYS Software Productions. Copyright©. All rights unreserved.
 */
public class addingReceptionist extends javax.swing.JFrame {

    /** Creates new form addingReceptionist */
    public addingReceptionist() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * Note from author: This code has been generated automatically from NETBEANS.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_addReceptionist = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textField_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textField_password = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textField_renterPassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textField_name = new javax.swing.JTextField();
        button_addUser = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        label_backToMainMenu = new javax.swing.JLabel();
        label_companyRights2 = new javax.swing.JLabel();
        label_companyRights1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Heriditary Blood Disorder Center HBDC");
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));
        setResizable(false);

        panel_addReceptionist.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Receptionist", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 102, 153))); // NOI18N

        label.setFont(new java.awt.Font("Tahoma", 1, 18));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Please fill in all the required fields to add a new user to the system");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Account Type:");

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Receptionist");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Username:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Re-enter Password:");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Name:");

        button_addUser.setText("Add User");
        button_addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addUserActionPerformed(evt);
            }
        });

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        label_backToMainMenu.setFont(new java.awt.Font("Tahoma", 0, 12));
        label_backToMainMenu.setForeground(new java.awt.Color(0, 0, 255));
        label_backToMainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_backToMainMenu.setText("Back to Main Menu");
        label_backToMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_backToMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_addReceptionistLayout = new javax.swing.GroupLayout(panel_addReceptionist);
        panel_addReceptionist.setLayout(panel_addReceptionistLayout);
        panel_addReceptionistLayout.setHorizontalGroup(
            panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addReceptionistLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addGroup(panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_username, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(textField_password, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(textField_renterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addReceptionistLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(button_addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(panel_addReceptionistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addReceptionistLayout.createSequentialGroup()
                        .addComponent(label_backToMainMenu)
                        .addGap(112, 112, 112))
                    .addGroup(panel_addReceptionistLayout.createSequentialGroup()
                        .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        panel_addReceptionistLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_addUser, button_cancel});

        panel_addReceptionistLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, textField_name, textField_password, textField_renterPassword, textField_username});

        panel_addReceptionistLayout.setVerticalGroup(
            panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addReceptionistLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(label)
                .addGap(58, 58, 58)
                .addGroup(panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_renterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(40, 40, 40)
                .addGroup(panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addGroup(panel_addReceptionistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_addUser)
                    .addComponent(button_cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(label_backToMainMenu))
        );

        label_companyRights2.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_companyRights2.setText("MHYS software productions");

        label_companyRights1.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights1.setText("Copyright©. All rights reserved.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_addReceptionist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_companyRights1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 527, Short.MAX_VALUE)
                        .addComponent(label_companyRights2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_addReceptionist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_companyRights2)
                    .addComponent(label_companyRights1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // If the admin want to return back to his control panel then the "Back to Main Menu" label when pressed makes the control panel visible.
    private void label_backToMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backToMainMenuMouseClicked
        new AdminControlPanel().setVisible(true);
    }//GEN-LAST:event_label_backToMainMenuMouseClicked

    /*
     * If the admin presses cancel button then all fields are set to the default
     * status which is blank.
     */
    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        textField_name.setText("");
        textField_password.setText("");
        textField_renterPassword.setText("");
        textField_username.setText("");
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addUserActionPerformed
        // Reading all values entered from the GUI.
        String name = textField_name.getText().trim();
        String password = textField_password.getText().trim();        
        String renterPassword = textField_renterPassword.getText().trim();        
        String username = textField_username.getText().trim();        

        /*
         * Condition to check if the admin has entered different passwords in
         * fields. If yes then an error message warns him of this mistake.
         */
        if(!(password.equals(renterPassword))){
           
           textField_password.setText("");
           textField_renterPassword.setText("");
           JOptionPane.showMessageDialog(null, "Password entered in the password fields do not match.","Error", JOptionPane.ERROR_MESSAGE);
        }

        /*
         * Condition to check if any of the required fields have been left empty.
         * If yes then an error message warns him of this mistake. Otherwise the
         * program goes on to add the doctor to the database.
         */
        if(name.equals("") || password.equals("") || renterPassword.equals("") || username.equals("")){
           JOptionPane.showMessageDialog(null, "One or more required fields are empty.\nPlease make sure you enter all the required fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        else{
            try{
                if(password.equals(renterPassword)){
                    // Creating new array list to import the entire receptionist database using the "Control" class.
                    ArrayList <Receptionist> r = new ArrayList<Receptionist>(Control.importReceptionistDatabase());

                    // Adding the new receptionist user to the array list.
                    r.add(new Receptionist(name,username,password));

                    // Printing the entire arraylist back to the file using the "Control" class.
                    Control.printReceptionistDatabase(r);

                    // Informs the admin that the new doctor was added successfully to the database.
                    System.out.println("A new receptionist was successfully added to the database by the admin.");
                    JOptionPane.showMessageDialog(null, "A new receptionist was successfully added to the database by the admin.");
                    
                    // All the fields in the GUI are set to the default state which is empty.
                    textField_username.setText("");
                    textField_password.setText("");
                    textField_renterPassword.setText("");
                    textField_name.setText("");
                }

             }
            // If there is an error reading the doctors from the file or writing the array list back to the file then the admin is notified about the error.
             catch(Exception e){
             JOptionPane.showMessageDialog(null, "Unable to write receptionist to the file.", "Error", JOptionPane.ERROR_MESSAGE);
             }

        }
        
    }//GEN-LAST:event_button_addUserActionPerformed

    /**
    * @param args the command line arguments
     * Note from author: This code has been generated automatically from NETBEANS.
     * 
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addingReceptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_addUser;
    private javax.swing.JButton button_cancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label_backToMainMenu;
    private javax.swing.JLabel label_companyRights1;
    private javax.swing.JLabel label_companyRights2;
    private javax.swing.JPanel panel_addReceptionist;
    private javax.swing.JTextField textField_name;
    private javax.swing.JTextField textField_password;
    private javax.swing.JTextField textField_renterPassword;
    private javax.swing.JTextField textField_username;
    // End of variables declaration//GEN-END:variables

}
