/*
 * Class name : AdminControlPanel.java
 *
 * Created on May 4, 2009, 8:19 PM
 *
 * Last Modified on June 12, 2009
 *
 * Why was this class created?
 * This class which is a GUI is the control panel for the administrator.
 * From here, the admin can view the features available to him/her and use
 * them to provide services to the hospital. He has the liberty to create a new
 * doctor and receptionist, remove any user, edit a user and print 2 kinds of
 * reports for the doctor.
 */

package hospital_project;

/**
 * @author  MHYS Software Productions. Copyright©. All rights unreserved.
 */
public class AdminControlPanel extends javax.swing.JFrame {

    
    /** Creates new form AdminControlPanel */
    public AdminControlPanel() {
        initComponents();

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * Note from author: This code has been generated automatically from NETBEANS.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_admin = new javax.swing.JPanel();
        icon_addUser = new javax.swing.JLabel();
        label_addDoctor = new javax.swing.JLabel();
        button_addDoctor = new javax.swing.JButton();
        label_addReceptionist = new javax.swing.JLabel();
        add_receptionist = new javax.swing.JButton();
        icon_removeUser = new javax.swing.JLabel();
        label_removeUser = new javax.swing.JLabel();
        button_removeUser = new javax.swing.JButton();
        icon_editUser = new javax.swing.JLabel();
        label_editUser = new javax.swing.JLabel();
        button_editUser = new javax.swing.JButton();
        icon_print = new javax.swing.JLabel();
        label_printReport = new javax.swing.JLabel();
        button_print = new javax.swing.JButton();
        icon_logout = new javax.swing.JLabel();
        icon_addUser1 = new javax.swing.JLabel();
        label_editUser1 = new javax.swing.JLabel();
        icon_editUser1 = new javax.swing.JLabel();
        button_editUser1 = new javax.swing.JButton();
        label_companyRights1 = new javax.swing.JLabel();
        label_companyRights2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Heriditary Blood Disorder Center HBDC");
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));
        setResizable(false);

        panel_admin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrator Control Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 102, 153))); // NOI18N

        icon_addUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_project/add_icon.gif"))); // NOI18N

        label_addDoctor.setFont(new java.awt.Font("Calibri", 1, 24));
        label_addDoctor.setText("1. Add a Doctor to the System");

        button_addDoctor.setText("Add Doctor");
        button_addDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addDoctorActionPerformed(evt);
            }
        });

        label_addReceptionist.setFont(new java.awt.Font("Calibri", 1, 24));
        label_addReceptionist.setText("2. Add a Receptionist to the System");

        add_receptionist.setText("Add Receptionist");
        add_receptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_receptionistActionPerformed(evt);
            }
        });

        icon_removeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_project/app-delete-35x35.png"))); // NOI18N

        label_removeUser.setFont(new java.awt.Font("Calibri", 1, 24));
        label_removeUser.setText("3. Remove a User");

        button_removeUser.setText("Remove User");
        button_removeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_removeUserActionPerformed(evt);
            }
        });

        icon_editUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_project/Icons-35X35-edit_user.png"))); // NOI18N

        label_editUser.setFont(new java.awt.Font("Calibri", 1, 24));
        label_editUser.setText("4. Edit Doctor");

        button_editUser.setText("Edit Doctor");
        button_editUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editUserActionPerformed(evt);
            }
        });

        icon_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_project/printer_icon.gif"))); // NOI18N

        label_printReport.setFont(new java.awt.Font("Calibri", 1, 24));
        label_printReport.setText("5. Print a Report");

        button_print.setText("Print");
        button_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_printActionPerformed(evt);
            }
        });

        icon_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_project/icon_logout.gif"))); // NOI18N
        icon_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_logoutMouseClicked(evt);
            }
        });

        icon_addUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_project/add_icon.gif"))); // NOI18N

        label_editUser1.setFont(new java.awt.Font("Calibri", 1, 24));
        label_editUser1.setText("4. Edit Receptionist");

        icon_editUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_project/Icons-35X35-edit_user.png"))); // NOI18N

        button_editUser1.setText("Edit Receptionist");
        button_editUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editUser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_adminLayout = new javax.swing.GroupLayout(panel_admin);
        panel_admin.setLayout(panel_adminLayout);
        panel_adminLayout.setHorizontalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_adminLayout.createSequentialGroup()
                        .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_addDoctor)
                            .addComponent(label_addReceptionist)
                            .addComponent(label_removeUser)
                            .addComponent(label_editUser)
                            .addComponent(label_editUser1)
                            .addComponent(label_printReport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_adminLayout.createSequentialGroup()
                                .addComponent(icon_addUser)
                                .addGap(18, 18, 18)
                                .addComponent(button_addDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_adminLayout.createSequentialGroup()
                                .addComponent(icon_addUser1)
                                .addGap(18, 18, 18)
                                .addComponent(add_receptionist))
                            .addGroup(panel_adminLayout.createSequentialGroup()
                                .addComponent(icon_removeUser)
                                .addGap(18, 18, 18)
                                .addComponent(button_removeUser))
                            .addGroup(panel_adminLayout.createSequentialGroup()
                                .addComponent(icon_editUser)
                                .addGap(18, 18, 18)
                                .addComponent(button_editUser))
                            .addGroup(panel_adminLayout.createSequentialGroup()
                                .addComponent(icon_editUser1)
                                .addGap(18, 18, 18)
                                .addComponent(button_editUser1))
                            .addGroup(panel_adminLayout.createSequentialGroup()
                                .addComponent(icon_print)
                                .addGap(18, 18, 18)
                                .addComponent(button_print))))
                    .addComponent(icon_logout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        panel_adminLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {add_receptionist, button_addDoctor, button_editUser, button_editUser1, button_print, button_removeUser});

        panel_adminLayout.setVerticalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_adminLayout.createSequentialGroup()
                        .addComponent(label_addDoctor)
                        .addGap(49, 49, 49)
                        .addComponent(label_addReceptionist)
                        .addGap(52, 52, 52)
                        .addComponent(label_removeUser)
                        .addGap(57, 57, 57)
                        .addComponent(label_editUser)
                        .addGap(61, 61, 61)
                        .addComponent(label_editUser1)
                        .addGap(68, 68, 68)
                        .addComponent(label_printReport))
                    .addGroup(panel_adminLayout.createSequentialGroup()
                        .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(button_addDoctor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icon_addUser, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(44, 44, 44)
                        .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(add_receptionist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icon_addUser1))
                        .addGap(47, 47, 47)
                        .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_removeUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icon_removeUser))
                        .addGap(52, 52, 52)
                        .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_editUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icon_editUser))
                        .addGap(56, 56, 56)
                        .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_editUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icon_editUser1))
                        .addGap(63, 63, 63)
                        .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icon_print))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(icon_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        label_companyRights1.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights1.setText("Copyright©. All rights reserved.");

        label_companyRights2.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_companyRights2.setText("MHYS software productions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_companyRights1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                        .addComponent(label_companyRights2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_companyRights1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_companyRights2))
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // When the "Add Receptionist" button is clicked, then a new window opens.
    private void add_receptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_receptionistActionPerformed
        new addingReceptionist().setVisible(true);
}//GEN-LAST:event_add_receptionistActionPerformed

    // When the "Logout" icon is clicked, then the login screen reopens.
    private void icon_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_logoutMouseClicked
        new loginScreen().setVisible(true);
    }//GEN-LAST:event_icon_logoutMouseClicked

    // When the "Add Doctor" button is clicked, then a new window opens.
    private void button_addDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addDoctorActionPerformed
        new addingDoctor().setVisible(true);
    }//GEN-LAST:event_button_addDoctorActionPerformed

    // When the "Remove User" button is clicked, then a new window opens.
    private void button_removeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_removeUserActionPerformed
        new removingUser().setVisible(true);
    }//GEN-LAST:event_button_removeUserActionPerformed

    // When the "Edit Doctor" button is clicked, then a new window opens.
    private void button_editUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editUserActionPerformed
        new editing_doctor().setVisible(true);
    }//GEN-LAST:event_button_editUserActionPerformed

    // When the "Edit Receptionist" button is clicked, then a new window opens.
    private void button_editUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editUser1ActionPerformed
        new editing_receptionist().setVisible(true);
    }//GEN-LAST:event_button_editUser1ActionPerformed

    // When the "Print Report" button is clicked, then a new window opens.
    private void button_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_printActionPerformed
        new printing_report().setVisible(true);
    }//GEN-LAST:event_button_printActionPerformed

    /**
    * @param args the command line arguments
     * Note from author: This code has been generated automatically from NETBEANS.
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminControlPanel().setVisible(true);
            }
        });
    }

    // Note from author: This code has been generated automatically from NETBEANS.
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_receptionist;
    private javax.swing.JButton button_addDoctor;
    private javax.swing.JButton button_editUser;
    private javax.swing.JButton button_editUser1;
    private javax.swing.JButton button_print;
    private javax.swing.JButton button_removeUser;
    private javax.swing.JLabel icon_addUser;
    private javax.swing.JLabel icon_addUser1;
    private javax.swing.JLabel icon_editUser;
    private javax.swing.JLabel icon_editUser1;
    private javax.swing.JLabel icon_logout;
    private javax.swing.JLabel icon_print;
    private javax.swing.JLabel icon_removeUser;
    private javax.swing.JLabel label_addDoctor;
    private javax.swing.JLabel label_addReceptionist;
    private javax.swing.JLabel label_companyRights1;
    private javax.swing.JLabel label_companyRights2;
    private javax.swing.JLabel label_editUser;
    private javax.swing.JLabel label_editUser1;
    private javax.swing.JLabel label_printReport;
    private javax.swing.JLabel label_removeUser;
    private javax.swing.JPanel panel_admin;
    // End of variables declaration//GEN-END:variables

}
