/*
 * Class name : doctors_patient_viewer.java
 *
 * Created on May 5, 2009, 1:29 PM
 *
 * Last Modified on June 12, 2009
 *
 * Why was this class created?
 * This GUI interface will allow the doctor to view the entire patient information
 * after he/she enters their file number as required in the GUI.
 */

package hospital_project;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * @author  MHYS Software Productions. Copyright©. All rights unreserved.
 */

public class doctors_patient_viewer extends javax.swing.JFrame {

    /** Creates new form doctors_patient_viewer */
    public doctors_patient_viewer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * Note from author: This code has been generated automatically from NETBEANS.
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_patientFileFound = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textField_name = new javax.swing.JTextField();
        textField_fileNumber = new javax.swing.JTextField();
        textField_dateOfBirth = new javax.swing.JTextField();
        textField_gender = new javax.swing.JTextField();
        textField_bloodType = new javax.swing.JTextField();
        textField_nationality = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_patientHistory = new javax.swing.JTextArea();
        button_edit = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        label_backToMainMenu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textField_file = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label_companyRights2 = new javax.swing.JLabel();
        label_companyRights1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Heriditary Blood Disorder Center HBDC");
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));
        setResizable(false);

        panel_patientFileFound.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient File Found", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("File number:");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Date Of Birth:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Gender:");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Blood type:");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Nationality:");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Patient history:");

        textField_name.setEditable(false);

        textField_fileNumber.setEditable(false);

        textField_dateOfBirth.setEditable(false);

        textField_gender.setEditable(false);

        textField_bloodType.setEditable(false);

        textField_nationality.setEditable(false);

        textArea_patientHistory.setColumns(20);
        textArea_patientHistory.setEditable(false);
        textArea_patientHistory.setLineWrap(true);
        textArea_patientHistory.setRows(5);
        jScrollPane1.setViewportView(textArea_patientHistory);

        button_edit.setText("Edit");
        button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editActionPerformed(evt);
            }
        });

        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        label_backToMainMenu.setFont(new java.awt.Font("Tahoma", 0, 12));
        label_backToMainMenu.setForeground(new java.awt.Color(0, 0, 255));
        label_backToMainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_backToMainMenu.setText("Back to Main Menu");
        label_backToMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_backToMainMenuMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Please enter the patient file number:");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_patientFileFoundLayout = new javax.swing.GroupLayout(panel_patientFileFound);
        panel_patientFileFound.setLayout(panel_patientFileFoundLayout);
        panel_patientFileFoundLayout.setHorizontalGroup(
            panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_patientFileFoundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_nationality, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addComponent(textField_bloodType, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addComponent(textField_gender, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addComponent(textField_dateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addComponent(textField_fileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_patientFileFoundLayout.createSequentialGroup()
                        .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_patientFileFoundLayout.createSequentialGroup()
                                .addComponent(textField_file, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(textField_name, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
                        .addGap(849, 849, 849)))
                .addContainerGap())
            .addGroup(panel_patientFileFoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label_backToMainMenu)
                        .addGroup(panel_patientFileFoundLayout.createSequentialGroup()
                            .addComponent(button_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
            .addGroup(panel_patientFileFoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(497, Short.MAX_VALUE))
        );

        panel_patientFileFoundLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_cancel, button_edit});

        panel_patientFileFoundLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, textField_bloodType, textField_dateOfBirth, textField_fileNumber, textField_gender, textField_name, textField_nationality});

        panel_patientFileFoundLayout.setVerticalGroup(
            panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_patientFileFoundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textField_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(48, 48, 48)
                .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_patientFileFoundLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textField_fileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textField_dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textField_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textField_bloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textField_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(textField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(panel_patientFileFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_save)
                    .addComponent(button_cancel)
                    .addComponent(button_edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(label_backToMainMenu)
                .addContainerGap())
        );

        label_companyRights2.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_companyRights2.setText("MHYS software productions");

        label_companyRights1.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights1.setText("Copyright©. All rights reserved.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_patientFileFound, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_companyRights1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 515, Short.MAX_VALUE)
                        .addComponent(label_companyRights2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_patientFileFound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_companyRights1)
                    .addComponent(label_companyRights2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // If the doctor wants to return back to his control panel then the "Back to Main Menu" label when pressed makes the control panel visible.
    private void label_backToMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backToMainMenuMouseClicked
        new doctor_controlpanel().setVisible(true);
}//GEN-LAST:event_label_backToMainMenuMouseClicked

    /* When the doctor presses the "Edit" button, this will allow him to
     * modify the patient history.
     */
    private void button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editActionPerformed
        textArea_patientHistory.setEditable(true);

    }//GEN-LAST:event_button_editActionPerformed

    /* When the doctor is done with the chages he/she wants to make to a patiennt's
     * history, then they press the "Save" button that allows them to save the
     * changes made to the patient history.
     */
    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        
        // Read the whole patient history into a String variable.
        String patientHistory = textArea_patientHistory.getText();

        // Boolean variable to show that the change to the patient history is made.
        boolean flag=false;

        // Gettin the pateint name and filenumber from the GUI.
        String pName = textField_name.getText().trim();
        String file = textField_fileNumber.getText().trim();

        // Initializing a new Array List to store Patient info from database.
        ArrayList<Patient> pat = new ArrayList<Patient>();

        // Importing the entire patient databse to the initialized Array List.
        pat = Control.importPatientDatabase();

        /* Looop to check if the patient is in the databse and then make the
         * change that will be recorded in a boolean variable.
         */
        
        for(Patient p:pat)
      	{
      		// Checking for a patient match from database to the one from GUI using name and file number.
            if(pName.equals(p.getName()) && file.equals(p.getFileNumber())){
                
                // Changing the patient history to the current one from GUI.
                p.setPatientHistory(patientHistory);

                // Changing the status of the boolean variable.
                flag=true;
            }
      	}
        Control.printPatientDatabase(pat);
        JOptionPane.showMessageDialog(null, "Pateint History successfully updated.");

        // If the patient is not found then no change in the boolean variable shows that patient was not found.
        if(!flag){
            JOptionPane.showMessageDialog(null, "Patient does not exist in databse.\n Kick him out of the hospital please.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_button_saveActionPerformed

    // this will make the pateint history information area non changeable by the doctor.
    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        textArea_patientHistory.setEditable(false);
        
    }//GEN-LAST:event_button_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String file = textField_file.getText().trim();
        if(file.equals("")){
            JOptionPane.showMessageDialog(null, "Search field is blank.\nPlease enter patient file number.","Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //try{

                ArrayList<Patient> pat = new ArrayList<Patient>();
                pat = Control.importPatientDatabase();
                for(Patient p:pat){
                    if(file.equals(p.getFileNumber())){
                        textField_name.setText(p.getName());
                        textField_fileNumber.setText(p.getFileNumber());
                        textField_dateOfBirth.setText(p.getDateOfBirth());
                        textField_gender.setText(p.getGender());
                        textField_bloodType.setText(p.getBloodType());
                        textField_nationality.setText(p.getNationality());
                        textArea_patientHistory.append(p.getPatientHistory());
                        
                    }
                }
           // }
           // catch(Exception e){
           //     JOptionPane.showMessageDialog(null, "Patient file does not exist.","Error", JOptionPane.ERROR_MESSAGE);
           // }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
     * Note from author: This code has been generated automatically from NETBEANS.
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctors_patient_viewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_edit;
    private javax.swing.JButton button_save;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_backToMainMenu;
    private javax.swing.JLabel label_companyRights1;
    private javax.swing.JLabel label_companyRights2;
    private javax.swing.JPanel panel_patientFileFound;
    private javax.swing.JTextArea textArea_patientHistory;
    private javax.swing.JTextField textField_bloodType;
    private javax.swing.JTextField textField_dateOfBirth;
    private javax.swing.JTextField textField_file;
    private javax.swing.JTextField textField_fileNumber;
    private javax.swing.JTextField textField_gender;
    private javax.swing.JTextField textField_name;
    private javax.swing.JTextField textField_nationality;
    // End of variables declaration//GEN-END:variables

}
