/*
 * Class name : doctor_controlpanel.java
 *
 * Created on May 5, 2009, 1:00 PM
 *
 * Last Modified on June 12, 2009
 *
 * Why was this class created?
 * This class which is a GUI is the control panel for the doctor.
 * From here, the doctor can view the features available to him/her and use
 * them to provide services to the hospital.
 * A doctor can view a patients information and modify the patient history.
 */

package hospital_project;

/*
 * @author  MHYS Software Productions. Copyright©. All rights unreserved.
 */

public class doctor_controlpanel extends javax.swing.JFrame {

    /** Creates new form doctor_controlpanel */
    public doctor_controlpanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * Note from author: This code has been generated automatically from NETBEANS.
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_doctorControlPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        button_search = new javax.swing.JButton();
        icon_logout = new javax.swing.JLabel();
        button_viewSchedule = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_companyRights1 = new javax.swing.JLabel();
        label_companyRights2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Heriditary Blood Disorder Center HBDC");
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));
        setResizable(false);

        panel_doctorControlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctor Control Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search for patient file and update information");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        button_search.setText("Search and Update");
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        icon_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_project/icon_logout.gif"))); // NOI18N
        icon_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_logoutMouseClicked(evt);
            }
        });

        button_viewSchedule.setText("View Schedule");
        button_viewSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewScheduleActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_project/view-log-icon.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_project/update_icon.png"))); // NOI18N

        javax.swing.GroupLayout panel_doctorControlPanelLayout = new javax.swing.GroupLayout(panel_doctorControlPanel);
        panel_doctorControlPanel.setLayout(panel_doctorControlPanelLayout);
        panel_doctorControlPanelLayout.setHorizontalGroup(
            panel_doctorControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_doctorControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_doctorControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_doctorControlPanelLayout.createSequentialGroup()
                        .addComponent(icon_logout)
                        .addGap(530, 530, 530)
                        .addComponent(button_viewSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                    .addGroup(panel_doctorControlPanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104)
                        .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        panel_doctorControlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_search, button_viewSchedule});

        panel_doctorControlPanelLayout.setVerticalGroup(
            panel_doctorControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_doctorControlPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_doctorControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_doctorControlPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_doctorControlPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(button_search, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addGap(314, 314, 314)
                .addGroup(panel_doctorControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon_logout)
                    .addComponent(button_viewSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_doctorControlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button_search, button_viewSchedule});

        label_companyRights1.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights1.setText("Copyright©. All rights reserved.");

        label_companyRights2.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_companyRights2.setText("MHYS software productions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_doctorControlPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_companyRights1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 517, Short.MAX_VALUE)
                        .addComponent(label_companyRights2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_doctorControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_companyRights2)
                    .addComponent(label_companyRights1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // When the button "Search and Update" is pressed, anew window opens.
    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
        new doctors_patient_viewer().setVisible(true);
    }//GEN-LAST:event_button_searchActionPerformed

    // When the "Logout" icon is clicked, then the login screen reopens.
    private void icon_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_logoutMouseClicked
        new loginScreen().setVisible(true);
    }//GEN-LAST:event_icon_logoutMouseClicked

    // When the button "View Schedule" is pressed a new window opens.
    private void button_viewScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewScheduleActionPerformed
        new doctor_view_schedule().setVisible(true);
    }//GEN-LAST:event_button_viewScheduleActionPerformed

    /**
    * @param args the command line arguments
     * Note from author: This code has been generated automatically from NETBEANS.
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctor_controlpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_search;
    private javax.swing.JButton button_viewSchedule;
    private javax.swing.JLabel icon_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label_companyRights1;
    private javax.swing.JLabel label_companyRights2;
    private javax.swing.JPanel panel_doctorControlPanel;
    // End of variables declaration//GEN-END:variables

}
