/*
 * patient_file_search_for_doctor.java
 *
 * Created on May 5, 2009, 1:20 PM
 */

package hospital_project;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author  st279245
 */

public class patient_file_search_for_doctor extends javax.swing.JFrame {

    /** Creates new form patient_file_search_for_doctor */
    public patient_file_search_for_doctor() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textField_fileNumber = new javax.swing.JTextField();
        button_search = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        label_backToMainMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Heriditary Blood Disorder Center HBDC");
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please enter the file number of the patient.");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24));
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("File Number:");

        textField_fileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_fileNumberActionPerformed(evt);
            }
        });

        button_search.setText("Search");
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        label_backToMainMenu.setFont(new java.awt.Font("Tahoma", 0, 12));
        label_backToMainMenu.setForeground(new java.awt.Color(0, 0, 255));
        label_backToMainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_backToMainMenu.setText("Back to Main Menu");
        label_backToMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_backToMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textField_fileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                            .addComponent(label_backToMainMenu))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_cancel, button_search});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textField_fileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_cancel)
                    .addComponent(button_search))
                .addGap(18, 18, 18)
                .addComponent(label_backToMainMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField_fileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_fileNumberActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_textField_fileNumberActionPerformed

    private void label_backToMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backToMainMenuMouseClicked
        new doctor_controlpanel().setVisible(true);
    }//GEN-LAST:event_label_backToMainMenuMouseClicked

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        textField_fileNumber.setText("");
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
        new doctors_patient_viewer().setVisible(true);

        String fileNumber = textField_fileNumber.getText().trim();
        if(fileNumber.equals("")){
            JOptionPane.showMessageDialog(null, "Search field is blank.\nPlease enter patient file number.","Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                ArrayList<Patient> pat = new ArrayList<Patient>();
                pat = Control.importPatientDatabase();
                for(Patient p:pat){
                    if(fileNumber.equals(p.getFileNumber())){
                        new doctors_patient_viewer().setVisible(true);
                    }
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Patient file does not exist.","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        //System.out.println(fileNumber);
        // searching operation goes here. 
    }//GEN-LAST:event_button_searchActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patient_file_search_for_doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label_backToMainMenu;
    private javax.swing.JTextField textField_fileNumber;
    // End of variables declaration//GEN-END:variables

}
