/*
 * Class name : receptionist_adding_patient.java
 *
 * Created on May 5, 2009, 1:53 PM
 *
 * Last Modified on June 12, 2009
 *
 * Why was this class created?
 * This GUI interface will allow the receptionist to add a ptient to the
 * existing system database.
 */

package hospital_project;
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author  MHYS Software Productions. Copyright©. All rights unreserved.
 */

public class receptionist_adding_patient extends javax.swing.JFrame {

    /** Creates new form receptionist_adding_patient */
    public receptionist_adding_patient() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * Note from author: This code has been generated automatically from NETBEANS.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_addPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textField_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textField_fileNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textField_dateOfBirth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textField_gender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textField_bloodType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textField_nationality = new javax.swing.JTextField();
        button_save = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        label_backToMainMenu = new javax.swing.JLabel();
        label_socialSecurityNumber = new javax.swing.JLabel();
        textField_socialSecurityNumber = new javax.swing.JTextField();
        label_companyRights2 = new javax.swing.JLabel();
        label_companyRights1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Heriditary Blood Disorder Center HBDC");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));
        setResizable(false);

        panel_addPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add patient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("File number:");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Date Of Birth:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Gender:");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Blood type:");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Nationality:");

        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        label_backToMainMenu.setFont(new java.awt.Font("Tahoma", 0, 12));
        label_backToMainMenu.setForeground(new java.awt.Color(0, 0, 255));
        label_backToMainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_backToMainMenu.setText("Back to Main Menu");
        label_backToMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_backToMainMenuMouseClicked(evt);
            }
        });

        label_socialSecurityNumber.setFont(new java.awt.Font("Calibri", 1, 18));
        label_socialSecurityNumber.setForeground(new java.awt.Color(0, 102, 153));
        label_socialSecurityNumber.setText("Social Security Number:");

        javax.swing.GroupLayout panel_addPanelLayout = new javax.swing.GroupLayout(panel_addPanel);
        panel_addPanel.setLayout(panel_addPanelLayout);
        panel_addPanelLayout.setHorizontalGroup(
            panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_name, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addPanelLayout.createSequentialGroup()
                        .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_fileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                            .addComponent(textField_dateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_gender, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
                    .addGroup(panel_addPanelLayout.createSequentialGroup()
                        .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(label_socialSecurityNumber, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_socialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField_nationality, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                            .addComponent(textField_bloodType, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                            .addGroup(panel_addPanelLayout.createSequentialGroup()
                                .addComponent(button_save, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addPanelLayout.createSequentialGroup()
                .addContainerGap(700, Short.MAX_VALUE)
                .addComponent(label_backToMainMenu)
                .addContainerGap())
        );

        panel_addPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textField_bloodType, textField_dateOfBirth, textField_fileNumber, textField_gender, textField_name, textField_nationality, textField_socialSecurityNumber});

        panel_addPanelLayout.setVerticalGroup(
            panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(textField_fileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_addPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textField_dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_bloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textField_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_socialSecurityNumber)
                    .addComponent(textField_socialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_save)
                    .addComponent(button_cancel))
                .addGap(242, 242, 242)
                .addComponent(label_backToMainMenu)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        label_companyRights2.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_companyRights2.setText("MHYS software productions");

        label_companyRights1.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights1.setText("Copyright©. All rights reserved.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(label_companyRights1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE)
                        .addComponent(label_companyRights2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_companyRights1)
                    .addComponent(label_companyRights2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // This allows the receptionist to return to the main menu.
    private void label_backToMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backToMainMenuMouseClicked
        new receptionist_controlpanel().setVisible(true);
    }//GEN-LAST:event_label_backToMainMenuMouseClicked

    // When the "Save" button is pressed then the following actions take place.
    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
       // To get the information entered in teh GUI.
       String name = textField_name.getText().trim();
       String fileNumber = textField_fileNumber.getText().trim();       
       String dateOfBirth = textField_dateOfBirth.getText().trim();    
       String gender = textField_gender.getText().trim();       
       String bloodType = textField_bloodType.getText().trim();       
       String nationality = textField_nationality.getText().trim();       
       String socialSecurityNumber = textField_socialSecurityNumber.getText().trim();
      // Initialize the patient history to nothing because they have just been added.
       String patientHistory = "No History";

       // condition to check if all fields are filled.
       if(name.equals("") || fileNumber.equals("") || dateOfBirth.equals("") || gender.equals("") || bloodType.equals("") || nationality.equals("") || socialSecurityNumber.equals("")){
           JOptionPane.showMessageDialog(null, "One or more required fields are empty.\nPlease make sure you enter all the required fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }

       try{
           // Initializing an array list of type Patient and importing data using "Control" class from the database.
           ArrayList <Patient> a = new ArrayList<Patient>(Control.importPatientDatabase());

           // Adding the user with the entered info to the array List.
           a.add(new Patient(name,nationality,socialSecurityNumber,fileNumber,dateOfBirth,gender,bloodType,patientHistory));

           //Writing back the Array List to the File.
           Control.printPatientDatabase(a);

           // Message to show that operation was successful.
            System.out.println("The patient was successfully added by the receptionist.");
            JOptionPane.showMessageDialog(null, "The patient was successfully added by the receptionist.");
       }
       // In case of any error of adding, message will be displayed.
       catch(Exception e){
            JOptionPane.showMessageDialog(null, "Unable to add patient to the database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
       

    }//GEN-LAST:event_button_saveActionPerformed

    // When the button "Cancel" is pressed, then the text fields are re-initialized to blank.
    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        textField_name.setText("");
        textField_fileNumber.setText("");
        textField_dateOfBirth.setText("");
        textField_gender.setText("");
        textField_bloodType.setText("");
        textField_nationality.setText("");
    }//GEN-LAST:event_button_cancelActionPerformed

    /**
    * @param args the command line arguments
     * 
     * Note from author: This code has been generated automatically from NETBEANS.
    */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receptionist_adding_patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_backToMainMenu;
    private javax.swing.JLabel label_companyRights1;
    private javax.swing.JLabel label_companyRights2;
    private javax.swing.JLabel label_socialSecurityNumber;
    private javax.swing.JPanel panel_addPanel;
    private javax.swing.JTextField textField_bloodType;
    private javax.swing.JTextField textField_dateOfBirth;
    private javax.swing.JTextField textField_fileNumber;
    private javax.swing.JTextField textField_gender;
    private javax.swing.JTextField textField_name;
    private javax.swing.JTextField textField_nationality;
    private javax.swing.JTextField textField_socialSecurityNumber;
    // End of variables declaration//GEN-END:variables

}
