/*
 * Class name : removingUser.java
 *
 * Created on May 5, 2009, 11:21 AM
 *
 * Last Modified on June 12, 2009
 *
 * Why was this class created?
 * This GUI interface will allow the admin to remove any system user.
 */

package hospital_project;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author  MHYS Software Productions. Copyright©. All rights unreserved.
 */

public class removingUser extends javax.swing.JFrame {

    /** Creates new form removingUser */
    public removingUser() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * Note from author: This code has been generated automatically from NETBEANS.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_removeUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textField_userName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboBox_accountType = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        button_delete = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        label_backToMainMenu = new javax.swing.JLabel();
        label_companyRights2 = new javax.swing.JLabel();
        label_companyRights1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Heriditary Blood Disorder Center HBDC");
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));
        setResizable(false);

        panel_removeUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remove User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please fill in all the required fields to delete user from the system");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Username:");

        comboBox_accountType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Doctor", "Receptionist", "Administrator" }));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Account Type:");

        button_delete.setText("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        label_backToMainMenu.setFont(new java.awt.Font("Tahoma", 0, 12));
        label_backToMainMenu.setForeground(new java.awt.Color(0, 0, 255));
        label_backToMainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_backToMainMenu.setText("Back to Main Menu");
        label_backToMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_backToMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_removeUserLayout = new javax.swing.GroupLayout(panel_removeUser);
        panel_removeUser.setLayout(panel_removeUserLayout);
        panel_removeUserLayout.setHorizontalGroup(
            panel_removeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_removeUserLayout.createSequentialGroup()
                .addGroup(panel_removeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_removeUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE))
                    .addGroup(panel_removeUserLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addGroup(panel_removeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_removeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_backToMainMenu)
                            .addGroup(panel_removeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textField_userName, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                                .addComponent(comboBox_accountType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_removeUserLayout.createSequentialGroup()
                                    .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        panel_removeUserLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_cancel, button_delete});

        panel_removeUserLayout.setVerticalGroup(
            panel_removeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_removeUserLayout.createSequentialGroup()
                .addGroup(panel_removeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_removeUserLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2))
                    .addGroup(panel_removeUserLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addGroup(panel_removeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textField_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(panel_removeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboBox_accountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(130, 130, 130)
                .addGroup(panel_removeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_delete)
                    .addComponent(button_cancel))
                .addGap(120, 120, 120)
                .addComponent(label_backToMainMenu)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        label_companyRights2.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_companyRights2.setText("MHYS software productions");

        label_companyRights1.setFont(new java.awt.Font("Tahoma", 0, 10));
        label_companyRights1.setText("Copyright©. All rights reserved.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_removeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_companyRights1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 511, Short.MAX_VALUE)
                        .addComponent(label_companyRights2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_removeUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_companyRights1)
                    .addComponent(label_companyRights2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // When the "Delete" button is pressed, then the following actions will take place.
    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed

        // reading username from the GUI.
        String userName = textField_userName.getText().trim();

        // boolean variable to record if the deleting operation is done to a doctor or receptionist.
        boolean flag1 = false, flag2 = false;

        // integer variables to record the position of the found user in their Array List.
        int index1=0 , index2=0;

        //Read the selected item from the combo box.
        String accountType = (String)comboBox_accountType.getSelectedItem();
        
        try{
            // condition to check if the user is a doctor.
            if(accountType.equals("Doctor")){
                // Array list of type "Doctor" is initialized and the information is imported using "Control" class and stored in the variable.
                ArrayList<Doctor> doc = new ArrayList<Doctor>(Control.importDocDatabase());
                // for each loop to record the position of the doctor that has to be removed.
                for(Doctor d:doc){
                    if(userName.equals(d.getUserName())){
                        // Recording the index of the doctor found to be deleted.
                        index1 = doc.indexOf(d);
                        flag1 = true;
                        break;
                    }
                }
                // if the doctor is found it is deleted.
                if(flag1){
                    doc.remove(index1);
                    JOptionPane.showMessageDialog(null, "User successfully deleted.");
                }
                // Then the array list is written back to the file.
                Control.printDoctorDatabase(doc);

            // the text fields in GUI are set to default status.
            textField_userName.setText("");
            comboBox_accountType.setSelectedIndex(0);
           }

         // condition to check if the user is a receptionist.
        if(accountType.equals("Receptionist")){

            // Array list of type "Doctor" is initialized and the information is imported using "Control" class and stored in the variable.
            ArrayList<Receptionist> rec = new ArrayList<Receptionist>(Control.importReceptionistDatabase());

            // for each loop to record the position of the receptionist that has to be removed.
            for(Receptionist r:rec){
                
                if(userName.equals(r.getUserName())){
                    // Recording the index of the receptionist found to be deleted.
                    index2 = rec.indexOf(r);
                    flag2 = true;
                    break;
                }
            }
            // if the doctor is found it is deleted.
            if(flag2){
                rec.remove(index2);
                JOptionPane.showMessageDialog(null, "User successfully deleted.");
            }
            // Then the array list is written back to the file.
            Control.printReceptionistDatabase(rec);

            // the text fields in GUI are set to default status.
            textField_userName.setText("");
            comboBox_accountType.setSelectedIndex(0);
            
        }
        // If no chages are made to the array list of doctor and receptionist, then message is printed.
        if(flag1==false && flag2==false){
            JOptionPane.showMessageDialog(null, "User does not exist in database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Unable to delete user.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_button_deleteActionPerformed

    // the text fields in GUI are set to default status.
    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        comboBox_accountType.setSelectedIndex(0);
        textField_userName.setText("");
    }//GEN-LAST:event_button_cancelActionPerformed

    // allows user to go back to the control panel.
    private void label_backToMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backToMainMenuMouseClicked
        new AdminControlPanel().setVisible(true);
    }//GEN-LAST:event_label_backToMainMenuMouseClicked

    /**
    * @param args the command line arguments
     * Note from author: This code has been generated automatically from NETBEANS.
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removingUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_delete;
    private javax.swing.JComboBox comboBox_accountType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_backToMainMenu;
    private javax.swing.JLabel label_companyRights1;
    private javax.swing.JLabel label_companyRights2;
    private javax.swing.JPanel panel_removeUser;
    private javax.swing.JTextField textField_userName;
    // End of variables declaration//GEN-END:variables

}
