/*
 * Class name : report_patient_history.java
 *
 * Created on Jun 11, 2009, 2:36:34 PM
 *
 * Last Modified on June 12, 2009
 *
 * Why was this class created?
 * This GUI interface will allow the admin to generate a report of patient history.
 */

package hospital_project;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author  MHYS Software Productions. Copyright©. All rights unreserved.
 */
public class report_patient_history extends javax.swing.JFrame {

    /** Creates new form report_patient_history */
    public report_patient_history() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * Note from author: This code has been generated automatically from NETBEANS.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textField_patient = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_report = new javax.swing.JTextArea();
        button_report = new javax.swing.JButton();
        button_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Heriditary Blood Disorder Center HBDC");
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Report - Medical History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Name of Patient:");

        textArea_report.setColumns(20);
        textArea_report.setEditable(false);
        textArea_report.setRows(5);
        jScrollPane1.setViewportView(textArea_report);

        button_report.setText("Generate Report");
        button_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_reportActionPerformed(evt);
            }
        });

        button_print.setText("Print Report");
        button_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(button_report)
                    .addComponent(button_print))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addComponent(textField_patient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_print, button_report});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textField_patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_report)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_print)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_reportActionPerformed
        // reading name of patient from the text field.
        String patient = textField_patient.getText().trim();

        textArea_report.append("\nFile Number" + "\t" + "Pateint Name" + "\t" + "Patient History" + "\n\n");
        
        // condition to check if the field is left blank.
        if(patient.equals("")){
            JOptionPane.showMessageDialog(null, "Field is blank.\nPlease enter the doctor's name.","Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                // Creating new array list of type "Patient" and storing info from the file using "Control" class.
                ArrayList<Patient> pat = new ArrayList<Patient>();

                pat = Control.importPatientDatabase();

                // for each loop to locate the patient in the array list.
                for(Patient p:pat){
                    if(patient.equals(p.getName())){
                        // displaying the patient information in the text area.
                        textArea_report.append(p.getFileNumber() + "\t" + p.getName() + "\t" + p.getPatientHistory() + "\n" );
                    }
                }

            }
            // in case of any exception error the following is displayed.
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Unexpected Error.\nCould not generate report.","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_button_reportActionPerformed

    // When the admin wants to print the report the following action takes place.
    private void button_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_printActionPerformed
        String patient = textField_patient.getText().trim();

        PrintWriter output=null;

     	try
     	{
     		output=new PrintWriter(new File(patient + " - report.txt"));
     	}
     	catch(FileNotFoundException e)
     	{
     		JOptionPane.showMessageDialog(null, "Unable to create report.", "Error", JOptionPane.ERROR_MESSAGE);
     	}

        ArrayList<Patient> pat = new ArrayList<Patient>();
        pat = Control.importPatientDatabase();

        output.println("File Number" + "\t" + "Patient Name" + "\t" + "Patient History" + "\n\n");

		for(Patient p:pat)
      	{
      		if(patient.equals(p.getName())){

      			output.print(p.getFileNumber()+ "\t" + p.getName() + "\t" + p.getPatientHistory());
      			output.println();
      		}

      	}
      	output.close();
        JOptionPane.showMessageDialog(null, "Report has been generated.\n Check file - " + patient + ".txt to print it.");
    }//GEN-LAST:event_button_printActionPerformed

    /**
    * @param args the command line arguments
     * Note from author: This code has been generated automatically from NETBEANS.
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report_patient_history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_print;
    private javax.swing.JButton button_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea_report;
    private javax.swing.JTextField textField_patient;
    // End of variables declaration//GEN-END:variables

}
